######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 7 22:38:06 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src src/interfaces src/lib src/ui src/modules/io
INCLUDEPATH += . src/ui src/lib src/interfaces src/modules/io

# Input
HEADERS += src/interfaces/interfaces.h \
           src/lib/graph.h \
           src/lib/macro.h \
           src/lib/module_manager.h \
           src/ui/mainwindow.h \
           src/modules/io/raw.h
SOURCES += src/main.cpp src/ui/mainwindow.cpp src/modules/io/raw.cpp
